name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.10
      with:
        clangFormatVersion: 11
        inplace: ""
  
  buildifier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: thompsonja/bazel-buildifier@v0.2.1
      with:
        warnings: all
