name: Build & Test

# Trigger for pushes and pull requests for all branches.
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-18.04

    env:
      LLVM_INSTALL_PATH: /usr/lib/llvm-11
  
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup LLVM deps
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main"
          sudo apt update
          sudo apt install -y lld-11 clang-11 lldb-11 llvm-11-dev libclang-11-dev liblldb-11-dev
      
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3

      - name: Build
        run: bazel build :all
      
      - name: Test
        run: bazel test --test_output=errors :all
